-- to auto update "updated_at" column
CREATE EXTENSION IF NOT EXISTS moddatetime;

CREATE TABLE schools
(
    id         VARCHAR(8)   NOT NULL PRIMARY KEY,
    version    INT          NOT NULL DEFAULT 0,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE book_categories
(
    id                   INT          NOT NULL PRIMARY KEY,
    version              INT          NOT NULL DEFAULT 0,
    letter               VARCHAR(1)   NOT NULL,
    name                 VARCHAR(256) NOT NULL,
    starting_book_id     INT          NOT NULL DEFAULT 0,
    ending_book_id       INT          NOT NULL DEFAULT 0,
    description          VARCHAR(32)  NOT NULL DEFAULT '',
    school_id            VARCHAR(8)   NOT NULL DEFAULT '',
    ccode_content_digits VARCHAR(256) NOT NULL DEFAULT '',
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uc_book_categories__letter UNIQUE (letter),
    CONSTRAINT fk_book_categories__school_id FOREIGN KEY (school_id) REFERENCES schools (id)
);


CREATE TABLE books
(
    id              INT          NOT NULL PRIMARY KEY,
    title           VARCHAR(256) NOT NULL,
    title_kana      VARCHAR(256),
    author          VARCHAR(256) NOT NULL,
    author_kana     VARCHAR(256),
    isbn            VARCHAR(32)  NOT NULL,
    comments        VARCHAR(511),
    publisher       VARCHAR(256) NOT NULL,
    date_added      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    is_missing      BOOLEAN,
    num_checkouts   INT          NOT NULL DEFAULT 0,
    date_deleted    DATE,
    date_lost       DATE,
    version         INT          NOT NULL DEFAULT 0,
    book_category_id INT         NOT NULL,
    school_id       VARCHAR(8)   NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (book_category_id) REFERENCES book_categories (id),
    FOREIGN KEY (school_id) REFERENCES schools (id)
);


CREATE TABLE members
(
     id           INT         NOT NULL PRIMARY KEY,
     date_added   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
     active       BOOLEAN     NOT NULL DEFAULT TRUE,
     class_number INT,
     grade        INT         NOT NULL DEFAULT 99,
     firstname_en VARCHAR(64) NOT NULL,
     lastname_en  VARCHAR(64) NOT NULL,
     firstname    VARCHAR(64),
     lastname     VARCHAR(64),
     school_id    VARCHAR(8),
     updated_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE checkouts
(
    member_id     INT  NOT NULL,
    book_id       INT  NOT NULL,
    checkout_date DATE NOT NULL,
    due_date      DATE NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (member_id, book_id),
    UNIQUE (book_id),
    FOREIGN KEY (member_id) REFERENCES members (id),
    FOREIGN KEY (book_id) REFERENCES books (id)
);

CREATE TABLE checkouts_history
(
    member_id     INT,
    book_id       INT,
    checkout_date DATE,
    due_date      DATE,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    operation     TEXT NOT NULL,       -- 'INSERT', 'UPDATE', or 'DELETE'
    changed_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_checkouts_history_member_id ON checkouts_history(member_id);
CREATE INDEX idx_checkouts_history_book_id ON checkouts_history(book_id);

CREATE TABLE limits
(
    role     VARCHAR(8)  NOT NULL,
    property VARCHAR(16) NOT NULL,
    value    VARCHAR(64) NOT NULL,
    PRIMARY KEY (role, property)
);


CREATE TABLE activities
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     INT         NOT NULL DEFAULT 0,
    book_id     INT         NOT NULL,
    member_id   INT,
    action_type VARCHAR(30) NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE checkout_limit_defaults
(
    id         INT        NOT NULL PRIMARY KEY,
    version    INT        NOT NULL DEFAULT 0,
    school_id  VARCHAR(8) NOT NULL,
    grade      INT        NOT NULL,
    max_books  INT        NOT NULL,
    max_days   INT        NOT NULL,
    created_at TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uc_checkout_limit_defaults__school_grade UNIQUE (school_id, grade),
    CONSTRAINT fk_checkout_limit_defaults__schools_id FOREIGN KEY (school_id) REFERENCES schools (id)
);

CREATE TABLE checkout_limit_schedules
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INT        NOT NULL DEFAULT 0,
    school_id     VARCHAR(8) NOT NULL,
    grade         INT        NOT NULL,
    schedule_date DATE       NOT NULL,
    max_books     INT        NOT NULL,
    max_days      INT        NOT NULL,
    created_at    TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uc_checkout_limit_schedules__school_grade_date UNIQUE (school_id, grade, schedule_date),
    CONSTRAINT fk_checkout_limit_schedules__schools_id FOREIGN KEY (school_id) REFERENCES schools (id)
);
