name: Publish container image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: "ghcr.io/${{ github.repository }}"

jobs:
  build:
    name: Build & Push to the Github Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: 'maven'
      - name: Get project version
        run: |
          VERSION=$( ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build and Test
        run: ./mvnw -B test
      - name: Deploy
        if: ${{ false }}  # Disable deploy
        run: ./mvnw -B -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Image
#        if: ${{ false }}  # Disable publishing image
        run: ./mvnw -B -DskipTests spring-boot:build-image -Dspring-boot.build-image.publish=true -Dspring-boot.build-image.imageName="${{ env.DOCKER_IMAGE_NAME }}"
        env:
          # configured to reference them in pom.xml
          DOCKER_REGISTRY_USER: ${{ github.actor }}
          DOCKER_REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
          CONTAINER_IMAGE_TAGS: "${{ env.DOCKER_IMAGE_NAME }}:latest,${{ env.DOCKER_IMAGE_NAME }}:${{ env.PROJECT_VERSION }}${{ contains(env.PROJECT_VERSION, 'snapshot') && format(',{0}:snapshot', env.DOCKER_IMAGE_NAME) || ''}}"
